version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "farheen"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1eaxn95dvpwil"
s3_prefix = "farheen"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
